## Basic Configuration
baseurl = "/"
languageCode = "en"

theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "gcabrerag-rbind-io"
googleAnalytics = "UA-124514267-1"
# enableRobotsTXT = true

ignoreFiles = ["\\.Rmd$","\\.Rmarkdown$","_files$", "_cache$"]

## Site Settings
[params]
    author = "Gabriel Cabrera"
    title = "Gabo's World"
    description = "Welcome to my little corner of the world"  
    authorimage = "/img/glitch.gif"
    dateformat = "Jan 1, 2006"
    
    highlightjs = true
    highlightjsTheme = "github" 
    highlightjsstyle = "github" 
    highlightjsLang = ["r", "yaml"]
    
    themeColor = "theme-base-0g" 

## Social Accounts
[params.social]
    github = "GaboCg"
  #  instagram = "GaboCg"
  #  xing = "<username>"
  #  linkedin = "<username>"
    twitter = "GaboC_g"
    facebook = "gabriel.cabrera.90"
  #  stackoverflow = "<username>"
    email = "gcabrerag@fen.uchile.cl"

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Teaching"
    identifier = "teaching"
    weight = 400
    url = "/teaching/"
[[menu.main]]
    name = "Shiny Apps"
    identifier = "shiny"
    weight = 500
    url = "http://shiny4fun.com/shiny/"
[[menu.main]]
    name = "Rstudio Server"
    identifier = "rstudio"
    weight = 600
    url = "http://shiny4fun.com/rstudio/"
[[menu.main]]
    name = "Tidytuesday (?)"
    identifier = "Tidy"
    weight = 700
    url = "https://gabocg.github.io/"
[[menu.main]]
    name = "Technical Notes"
    identifier = "Notes"
    weight = 800
    url = "https://technotes.netlify.com/"

