---
title: 'Finanzas I '
author: 'Gabriel Cabrera '
date: '2018-07-26'
slug: finanzas-i
categories:
  - FInance
tags:
  - R
output:
  blogdown::html_page:
    toc: false
    fig_width: 8
    css: ["/css/bootstrap.css"]
---

# Material de clases

## Apunte: Introducción a las finanzas quantitativas

* Apunte de R para Finanzas I : [https://finance-r.netlify.com/](https://finance-r.netlify.com/)


    <div class="btn-group">

    <br>
    <button type="button" class="btn btn-outline-warning"> 
    [Apunte](https://finance-r.netlify.com/)
    </button>
  
    <button type="button" class="btn btn-outline-warning"> 
    [*Code Source*](https://github.com/GaboCg/bookdown_finance)
    </button>
    <br>
    
    </div>


## Ayudantías 

a. Ayudantía 1: Introducción a R

    * R y Rstudio
    * Creación de un proyecto
    * Scripts
    * Instalación de librerías/packages
    * Tidyverse

    <div class="btn-group">

    <br>
    <button type="button" class="btn btn-outline-warning"> 
    [Presentación](/pdf/presentacion.pdf)
    </button>
    
    <button type="button" class="btn btn-outline-warning"> 
     Script
    </button>

    <button type="button" class="btn btn-outline-warning"> 
    *Code Source*
    </button>
    <br>
    
    </div>
    
b. Ayudantía 2: Introducción a Quantmod 

    * Obtención de Datos
    * Gráficos usando Quantmod
    * Trabajando con múltiples datos
    * Estadística Descriptiva
    
    <div class="btn-group">

    <br>
    <button type="button" class="btn btn-outline-warning"> 
    [Presentación](/pdf/presentation1.pdf)
    </button>
    
    <button type="button" class="btn btn-outline-warning"> 
     Script
    </button>

    <button type="button" class="btn btn-outline-warning"> 
    *Code Source*
    </button>
    <br>
    
    </div>
    
c. Ayudantía 3 
    
    <div class="btn-group">

    <br>
    <button type="button" class="btn btn-outline-warning"> 
    [Presentación](/pdf/presentation2.pdf)
    </button>
    
    <button type="button" class="btn btn-outline-warning"> 
     Script
    </button>

    <button type="button" class="btn btn-outline-warning"> 
    *Code Source*
    </button>
    <br>
    
    </div>

d. Ayudantía 4 
    
    <div class="btn-group">

    <br>
    <button type="button" class="btn btn-outline-warning"> 
    [Presentación](/pdf/Bond_presentation.pdf)
    </button>
    
    <button type="button" class="btn btn-outline-warning"> 
     Script
    </button>

    <button type="button" class="btn btn-outline-warning"> 
    *Code Source*
    </button>
    <br>
    
    </div>

e. Ayudantía 5 
    
    <div class="btn-group">

    <br>
    <button type="button" class="btn btn-outline-warning"> 
    [Presentación](/pdf/presentacion.pdf)
    </button>
    
    <button type="button" class="btn btn-outline-warning"> 
     Script
    </button>

    <button type="button" class="btn btn-outline-warning"> 
    *Code Source*
    </button>
    <br>
    
    </div>

## Tutoriales

<iframe width="420" height="315"
src="https://youtu.be/TwBKLTq3mfY">
</iframe>

* [Introducción a quantmod](https://youtu.be/TwBKLTq3mfY)
* [Retorno y Retorno Acumulado](https://youtu.be/-3RvuhtfNGU)
* [Graficar y Estadística Descriptiva](https://youtu.be/qlLFjBMSUlQ)
        
        
## Tareas 

a. Tarea 1 
    
    * [Enunciado](/pdf/Enunciado_v1.pdf)

b. Tarea 2

    * Enunciado