---
title: Business Intelligence for finance
author: ''
date: '2019-08-12'
slug: business-intelligence-para-las-finanzas
categories: []
tags: []
lastmod: '2019-08-12T14:15:37-04:00'
layout: post
type: post
highlight: no
---

```{r, echo=FALSE, eval=TRUE}
library(fontawesome)
```

# Apunte

* `r fa("desktop", fill = "purple")` [Ver Posts](https://technotes.netlify.com/python/_site/)

# Slides

# Ayudantías 

| Nº  | Descripción                      |Enunciado                                                   |Python Script                       |R Script                              |
|:---:|:---                              |:---:                                                       |:---:                               |:---:                                 |
|1    |Introducción a Jupyter Notebook   |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A1.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|2    |Introducción a Numpy              |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A1.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|3    |Introducción a Pandas             |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A2.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|4    |Concatenar & Merge                |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A2.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|5    |Descargar Datos Financieros       |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A2.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|6    |Complejidad Computacional         |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A3.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|7    |Gradiente Descendiente            |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A4.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|8    |Regresión Lineal                  |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A4.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|9    |Regresión Logística               |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A4.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|10   |Regresión Polinomial              |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A5.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|11   |Modelos Regularizado              |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A5.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|12   |Modelos Multinomial               |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A6.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|13   |Support Vector Machines           |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A6.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|14   |Redes Neuronales Artificiales     |[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A7.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|15   |Entropía & Ganancia de Información|[`r fa("file-pdf", fill = "red")`](/pdf/bi_4_finance/A8.pdf)|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|16   |Árboles de Decisión               |[`r fa("file-pdf", fill = "red")`]()                        |[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|17   |Random Forest                     |[`r fa("file-pdf", fill = "red")`]()                        |[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
|18   |Introducción a Deep Learning      |[`r fa("file-pdf", fill = "red")`]()                        |[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
 
# Tareas 

* Primavera 2019

    | Nº  | Descripción                      |Enunciado                           |Python Script                       |R Script
    |:---:|:---                              |:---:                               |:---:                               |:---:                                 |  
    |1    |Introducción tidyquant            |[`r fa("file-pdf", fill = "red")`]()|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
    |2    |Retorno y Retorno Acumulado       |[`r fa("file-pdf", fill = "red")`]()|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|
    
# Midterm Exam 

* Primavera 2019

    | Nº  | Descripción                      |Enunciado                           |Python Script                       |R Script
    |:---:|:---                              |:---:                               |:---:                               |:---:                                 |  
    |1    |Introducción tidyquant            |[`r fa("file-pdf", fill = "red")`]()|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|

# Final Exam  

* Primavera 2019

    | Nº  | Descripción                      |Enunciado                           |Python Script                       |R Script
    |:---:|:---                              |:---:                               |:---:                               |:---:                                 |  
    |1    |Introducción tidyquant            |[`r fa("file-pdf", fill = "red")`]()|[`r fa("python", fill = "green")`]()|[`r fa("r-project", fill = "blue")`]()|