---
draft: true
title: "Technical Analysis With Plotly" 
author: 'Gabriel Cabrera'
date: '2018-08-23'
slug: technical-analysis-with-plotly
categories: []
tags: []
---

```{r, echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE}
if(!require("pacman")) install.packages("pacman")
p_load("plotly", "quantmod")
```

# get data

```{r, echo = TRUE, eval = TRUE, warning=FALSE, message=FALSE}
GSPC <- getSymbols("^GSPC",src='yahoo',auto.assign = FALSE, from = "2007-01-01")
df <- data.frame(Date=index(GSPC),coredata(GSPC))
```

# create Bollinger Bands

```{r, echo = TRUE, eval = TRUE}
bbands <- BBands(GSPC[,c("GSPC.High","GSPC.Low","GSPC.Close")])
```

# join and subset data

```{r, echo = TRUE, eval = TRUE}
df <- subset(cbind(df, data.frame(bbands[,1:3])), Date >= "2015-01-01")
```


# colors column for increasing and decreasing

```{r, eval = TRUE, echo = TRUE}
for (i in 1:length(df[,1])) {
  if (df$GSPC.Close[i] >= df$GSPC.Open[i]) {
    df$direction[i] = 'Aumento'
  } else {
    df$direction[i] = 'Disminución'
  }
}
```
 
```{r, eval = TRUE, echo = TRUE}
i <- list(line = list(color = '#17BECF'))
d <- list(line = list(color = '#7F7F7F'))
```


# plot candlestick chart

```{r}
p <- df %>%
     plot_ly(x = ~Date, type="candlestick",
             open = ~GSPC.Open, close = ~GSPC.Close,
             high = ~GSPC.High, low = ~GSPC.Low, name = "GSPC",
             increasing = i, decreasing = d) %>%
     add_lines(x = ~Date, y = ~up , name = "B Bands",
               line = list(color = '#ccc', width = 0.5),
               legendgroup = "Bollinger Bands",
               hoverinfo = "none", inherit = F) %>%
     add_lines(x = ~Date, y = ~dn, name = "B Bands",
               line = list(color = '#ccc', width = 0.5),
               legendgroup = "Bollinger Bands", inherit = F,
               showlegend = FALSE, hoverinfo = "none") %>%
     add_lines(x = ~Date, y = ~mavg, name = "Mv Avg",
               line = list(color = '#E377C2', width = 0.5),
               hoverinfo = "none", inherit = F) %>%
     layout(yaxis = list(title = "Price"))
```


# plot volume bar chart


```{r}
pp <- df %>%
      plot_ly(x=~Date, y=~GSPC.Volume, type='bar', name = "GSPC Volumen",
              color = ~direction, colors = c('#17BECF','#7F7F7F')) %>%
      layout(yaxis = list(title = "Volume"))
```


# create rangeselector buttons
```{r}
rs <- list(visible = TRUE, x = 0.5, y = -0.055,
           xanchor = 'center', yref = 'paper',
           font = list(size = 9),
           buttons = list(
             list(count=1,
                  label='RESET',
                  step='all'),
             list(count=1,
                  label='1 YR',
                  step='year',
                  stepmode='backward'),
             list(count=3,
                  label='3 MO',
                  step='month',
                  stepmode='backward'),
             list(count=1,
                  label='1 MO',
                  step='month',
                  stepmode='backward')
           ))
```


# subplot with shared x axis
```{r}
p <- subplot(p, pp, heights = c(0.7,0.2), nrows=2, shareX = TRUE, titleY = TRUE) %>%
     layout(title = paste("S&P 500: 2015-01-01",Sys.Date()),
             xaxis = list(rangeselector = rs),
             legend = list(orientation = 'h', x = 0.5, y = 1,
                           xanchor = 'center', yref = 'paper',
                           font = list(size = 10),
                           bgcolor = 'transparent'))
```   

<center>
```{r, echo=FALSE}
p
```
</center>



