---
title: Road to oscars 2019
author: 'Gabriel Cabrera '
date: '2019-02-04'
slug: road-to-oscars-2019
categories:
  - Rstat
  - DataViz
tags:
  - ggplot2
lastmod: '2019-02-04T16:39:01-03:00'
layout: post
type: post
highlight: no
---

```{r, echo = TRUE, message = FALSE}
if(!require("pacman")) install.packages("pacman")
p_load("tidyverse", "rvest", "bbplot", "ggalt")
```

```{r}
oscar_movies <- read_html("https://www.imdb.com/list/ls023438886/?st_dt=&mode=detail&page=1&ref_=ttls_vm_dtl&sort=list_order,asc")
```

```{r}  
matrix_value <- matrix(0, nrow = 36, ncol = 4)

colnames(matrix_value) <- c("movie_name", "date", "imdb_score", "metacritic_score")

```

```{r}
for(i in 1:36){
  
  seudo_link <- "#main > div > div.lister.list.detail.sub-list > div.lister-list > div:nth-child"
  selector <- c("a", "span.lister-item-year.text-muted.unbold")

  for(j in 1:2){
    
    matrix_value[i,j] <- oscar_movies %>% 
    html_nodes(paste0(seudo_link,"(",i,") ","> div.lister-item-content > h3 > ",selector[j])) %>% 
    html_text() %>% 
    as.character()
     
  }
  
  matrix_value[i,3] <- oscar_movies %>% 
    html_nodes(paste0(seudo_link,"(",i,") ","> div.lister-item-content > div.ipl-rating-widget > div.ipl-rating-star.small > span.ipl-rating-star__rating")) %>% 
    html_text() %>% 
    as.numeric()

  matrix_value[i,4] <- oscar_movies %>% 
    html_nodes(paste0(seudo_link,"(",i,") ","> div.lister-item-content > div.inline-block.ratings-metascore > span")) %>% 
    html_text() %>% 
    as.numeric()  
}
```

```{r}
oscar_df <-  as.data.frame(matrix_value) %>% 
  mutate(movie_name = as.character(movie_name),
         date = as.character(date),
         imdb_score = as.numeric(as.character(imdb_score))*10,
         metacritic_score = as.numeric(as.character(metacritic_score)))

```

```{r}
dumbell_df <- oscar_df %>% 
  mutate(gap = metacritic_score - imdb_score,
         movie_name = replace(movie_name, movie_name == "Han Solo: Una Historia de Star Wars", "Han Solo"),
         movie_name = replace(movie_name, movie_name == "Ready Player One: Comienza el Juego", "Ready Player One"),
         movie_name = replace(movie_name, movie_name == "Bohemian Rhapsody, La historia de Freddie Mercury", "Bohemian Rhapsody")) %>% 
  arrange(desc(gap))
```

```{r, fig.width= 16, fig.height= 12, fig.align='center', warnigs = FALSE}
ggplot(dumbell_df, aes(x = imdb_score, xend = metacritic_score,
                       y = reorder(movie_name, gap), group = movie_name)) +
  geom_dumbbell(colour = "#dddddd",
                size = 3,
                colour_x = "#FAAB18",
                colour_xend = "#1380A1") +
  geom_label(aes(x=80, y= "Hale County This Morning, This Evening", label="Critic rating"),
                    color="#1380A1", hjust=0, size=4, nudge_x=5.5, fontface = "bold", 
             fill = "white", label.size = NA) + 
  geom_label(aes(x=68, y= "Hale County This Morning, This Evening", label="Audience rating"),
                    color="#FAAB18", hjust=0, size=4, nudge_x=-9, fontface = "bold", 
             fill = "white", label.size = NA) +
  bbc_style() + 
  theme(plot.title=element_text(hjust = 0),
        plot.subtitle=element_text(hjust = 0)) + 
  scale_x_continuous(limits=c(40, 100),
                     breaks = seq(40, 100, by = 10),
                     labels = c("Lower","50", "60", "70", "80", "90", "Higher")) + 
  labs(title = "Como los críticos y la audencia votan",
       subtitle ="Diferencia entre el puntaje promedio de los críticos y la audencia. \nPelículas nominadas a los Oscars 2019")
```





